### ISSUE TITLE
Add xformers support

### ISSUE THREAD

**Issue by xuzhao9** [pytorch-labs/tritonbench#20]
Add xformers built on source code, similar to fbgemm: https://github.com/facebookresearch/xformers

Make sure fa3 is available.

**Comment by antferdom** [comment]
Simple op availability assertion:
```python
op = xformers.ops.fmha.flash3.FwOp
if op.is_available():
    print(f"xformers_ops_fmha_flash3 supported: {HAS_FLASH}")
```
# References

- [xformers flash3 dispatch logic](https://github.com/facebookresearch/xformers/blob/a97a1e0cb4337b0a8a8ee1670618a1f15fb84f54/xformers/ops/fmha/dispatch.py#L83)
- `python -m xformers.info`
```bash
memory_efficient_attention.fa3F@0.0.0:             available
memory_efficient_attention.fa3B@0.0.0:             available
```

**Comment by xuzhao9** [comment]
https://github.com/pytorch-labs/tritonbench/pull/23 should fix this

**Comment by antferdom** [comment]
Looks good to me, but xformers build from sources with [FA3 support might trigger recompilation](https://github.com/facebookresearch/xformers/blob/a97a1e0cb4337b0a8a8ee1670618a1f15fb84f54/setup.py#L299) in the existing environment and overlap with previous Flash Attention v3 installation.

**Comment by xuzhao9** [comment]
Yes I think it is a valid issue to post to the xformers repo @antferdom

**Comment by xuzhao9** [comment]
I took a further look at xformers code, since we are compiling it from source, I think it should build the `xformers._C_flashattention3` plugin at https://github.com/facebookresearch/xformers/blob/6e10bd21ac6fc878657b24684723ccd05e41d385/setup.py#L321C19-L321C46 and should not fallback to the preinstalled `flashattn_hopper_cuda ` package.

To me there seems to have no problem and no conflict. What do you think?

**Comment by xuzhao9** [comment]
Actually the xformers FA3 build is broken, submitted: https://github.com/facebookresearch/xformers/pull/1157

**Comment by ohwi** [comment]
Hi. I'm Hwigeon, working with @antferdom.

If my memory serves me correctly (apologies, it's been a month since I last tried this), I moved to a newer version of FA because I also couldn't compile FA with xFormers, which led to the problem mentioned above.

**Comment by xuzhao9** [comment]
@ohwi Can you please try with https://github.com/facebookresearch/xformers/pull/1157 to see if FA works with xformers?

**Comment by ohwi** [comment]
Sure, I will try with your solution in a day

**Comment by antferdom** [comment]
> Actually the xformers FA3 build is broken, submitted: [facebookresearch/xformers#1157](https://github.com/facebookresearch/xformers/pull/1157)
> After this patch, we can install xformer+FA3 and FA3 as separate kernel impls for flash_attention and they won't conflict.

Are we going to use ` libraries=["cuda"]` patch workaround until upstream FA3 fix and upgrade CUTLASS? Should we then forward this issue to FlashAttention repo? @lw explained it with great detail showcasing the underlying problematic beyond what we thought.  Will try with @ohwi

**Comment by xuzhao9** [comment]
@antferdom  Yes, we are going to patch xformers until it updates FA3 and CUTLASS.

**Comment by antferdom** [comment]
@xuzhao9 alright, thanks for the clarification. It does makes sense for us as well, since we have complete control over the machines. I have use [Tritonbench Dockerfile](https://github.com/pytorch-labs/tritonbench/blob/main/docker/tritonbench-nightly.dockerfile) as main reference for us to have [almost identical environment as yours](https://github.com/ai-compiler-study/test_attn/blob/main/docker/test-attn-nightly.dockerfile), and can validate that trying your patch, xformers works:
```bash
$ python -c "import xformers._C_flashattention3"
```
