### ISSUE TITLE
Need general flops metric from ncu report

### ISSUE THREAD

**Issue by FindHao** [pytorch-labs/tritonbench#33]

**Comment by xuzhao9** [comment]
Let's differentiate this with the current `tflops()` metric, the ncu report is the hardware flops where the current tflops is analytic flops (calculated from math).

**Comment by xuzhao9** [comment]
how about we use a shorter name `hw_tflops` or `ncu_tflops`?

**Comment by FindHao** [comment]
> how about we use a shorter name `ncu_tflops`?

sure. will add this feature later.

**Comment by antferdom** [comment]
@xuzhao9 What about using Triton's Proton profiler metadata metric scope instead? see [Triton and cuBLAS matmul kernel](https://github.com/triton-lang/triton/blob/38a11b859fff79ea214256d3f1cfe43d54e36c2c/third_party/proton/tutorials/matmul.py#L267)

**Comment by FindHao** [comment]
> @xuzhao9 What about using Triton's Proton profiler metadata metric scope instead? see [Triton and cuBLAS matmul kernel](https://github.com/triton-lang/triton/blob/38a11b859fff79ea214256d3f1cfe43d54e36c2c/third_party/proton/tutorials/matmul.py#L267)

We had some discussions here https://github.com/pytorch/pytorch/pull/136169. I think we are open to do in proton way too if anyone wants to help. I've got a ncu version locally and will push it later.

**Comment by antferdom** [comment]
@xuzhao9 Thanks for the clarification about the target FLOPs number, “analytic flops” (e.g. user defined formula like in Proton) vs NCU GPU hardware counters for precise flops counting. I’m also currently using ncu for automatically profiling [Torch Inductor Triton GPU kernels](https://github.com/ai-compiler-study/test_attn/blob/main/inductor_profiling.py), based on Torch official documentation. `@register_metric()`  is similar to Proton’s `metric` in scope and `metadata_fn`

@FindHao I have a simple prototype for automatically annotating using Proton `scope` contextmanager, as discussed in the issue. Before going further with Proton, I will wait for your ncu runner exemple.

**Comment by FindHao** [comment]
> @xuzhao9 Thanks for the clarification about the target FLOPs number, “analytic flops” (e.g. user defined formula like in Proton) vs NCU GPU hardware counters for precise flops counting. I’m also currently using ncu for automatically profiling [Torch Inductor Triton GPU kernels](https://github.com/ai-compiler-study/test_attn/blob/main/inductor_profiling.py), based on Torch official documentation. `@register_metric()` is similar to Proton’s `metric` in scope and `metadata_fn`
> 
> @FindHao I have a simple prototype for automatically annotating using Proton `scope` contextmanager, as discussed in the issue. Before going further with Proton, I will wait for your ncu runner exemple.

The key part to obtain flops is done here https://github.com/pytorch-labs/tritonbench/blob/main/tritonbench/components/ncu/analyzer.py#L86 . The remaining parts are aggregation and add metrics to results. will do it later.
